import React from 'react';

export const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 space-y-8 prose prose-invert">
      <h1 className="text-4xl font-bold text-white">Privacy Policy</h1>
      <p className="text-zinc-400">Last updated: March 30, 2026</p>
      
      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-white">1. Information We Collect</h2>
        <p className="text-zinc-400">
          We collect information you provide directly to us when you create an account, use our AI tools, or communicate with us. This includes your email address, display name, and the text inputs you provide to our AI generators.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-white">2. How We Use Your Information</h2>
        <p className="text-zinc-400">
          We use the information we collect to:
        </p>
        <ul className="list-disc pl-6 text-zinc-400">
          <li>Provide, maintain, and improve our services.</li>
          <li>Process your AI generation requests.</li>
          <li>Send you technical notices and support messages.</li>
          <li>Monitor and analyze trends, usage, and activities.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-white">3. AI Content Generation</h2>
        <p className="text-zinc-400">
          The content generated by our AI tools is processed using Google's Gemini API. While we store your generation history for your convenience, we do not use your private data to train our models.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-white">4. Data Security</h2>
        <p className="text-zinc-400">
          We use Firebase's industry-standard security measures to protect your data. However, no method of transmission over the internet is 100% secure.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-white">5. Contact Us</h2>
        <p className="text-zinc-400">
          If you have any questions about this Privacy Policy, please contact us at support@ytgrowthai.com.
        </p>
      </section>
    </div>
  );
};
